name: Protfilio Deploynent

on:
 push:
  branches:
      -main
      
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: actions/@checkoutv1
    
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secretes.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secretes.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-south-1
      
  - name: Deploy static site to s3 bucket
    run: aws s3 sync . s3://tws-protfolio --delete
      
                
